<?php
$pagesNo = $item->getProperty('pagesno',1,'is_integer');
$ctrl_params = array(
    'tagid'=>'df_template_design_edit_form',
    'response_target'=>'df_template_design_edit_errors',
    'colsno'=>1,
    'content'=>array(
        array(
            array(
                'control_type'=>'SmartComboBox',
                'control_params'=>array('tagid'=>'df_template_design_edit_render_type','label'=>Translate::GetLabel('render_type'),
                    'tagname'=>'render_type',
                    'required'=>TRUE,
                    'valfield'=>'id',
                    'displayfield'=>'name',
                    'selectedvalue'=>$item->getProperty('render_type',1,'is_integer'),
                    'state_field'=>'state',
                    'load_type'=>'database',
                    'data_source'=>array(
                        'ds_class'=>'_Custom\Offline',
                        'ds_method'=>'GetDynamicFormsDesignRenderTypes',
                        'ds_params'=>['for_type'=>$pagesNo>1 ? 2 : 1],
                    ),
                ),
            ),
        ),
        array(
            array(
                'control_type'=>'TextBox',
                'control_params'=>array('tagid'=>'df_template_design_edit_theme_type','tagname'=>'theme_type','value'=>$item->getProperty('theme_type','','is_string'),'label'=>Translate::GetLabel('theme_type'),'onenterbutton'=>'df_template_design_edit_save'),
            ),
        ),
        array(
            array(
                'control_type'=>'TextBox',
                'control_params'=>array('tagid'=>'df_template_design_edit_controls_size','tagname'=>'controls_size','value'=>$item->getProperty('controls_size','','is_string'),'label'=>Translate::GetLabel('controls_size'),'onenterbutton'=>'df_template_design_edit_save'),
            ),
        ),
        array(
            array(
                'control_type'=>'NumericTextBox',
                'control_params'=>array('tagid'=>'df_template_design_edit_label_cols','tagname'=>'label_cols','value'=>$item->getProperty('label_cols','','is_integer'),'label'=>Translate::GetLabel('label_cols'),'allownull'=>TRUE,'numberformat'=>'0|||','onenterbutton'=>'df_template_design_edit_save'),
            ),
        ),
        array(
            array(
                'control_type'=>'TextBox',
                'control_params'=>array('tagid'=>'df_template_design_edit_separator_width','tagname'=>'separator_width','value'=>$item->getProperty('separator_width','','is_string'),'label'=>Translate::GetLabel('separator_width'),'onenterbutton'=>'df_template_design_edit_save'),
            ),
        ),
    ),
    'actions'=>array(
        array(
            'params'=>array('tagid'=>'df_template_design_edit_save','value'=>Translate::GetButton('save'),'icon'=>'fa fa-save','onclick'=>NApp::Ajax()->Prepare("AjaxRequest('{$this->class}','EditDesignRecord','id_template'|{$idTemplate}~df_template_design_edit_form:form,'df_template_design_edit_form')->df_template_design_edit_errors")),
        ),
    ),
);